### ISSUE TITLE
Upgrade Requested when use http server + ws server

### ISSUE THREAD

**Issue by Vaann00** [RodrigoBertotti/askless-flutter-client#1]
Hello,

Thank you for your work.
I have an issue with the use of the init part.
I am working with Flutter and nodejs and I have a HTTP server on heroku that is configured.
I want to work with both HTTP Server and Ws but it keeps saying Upgrade required as soon as I request the HTTP calls.
Here is my code :

Client call to API : 

  Future<TokenManager> RefreshToken(String refreshToken) async {
    String url = ADDRESS_SERVER + API_VERSION + '/token';
    Map<String, String> headers = {'Accept': 'application/json', 'Content-Type': 'application/json'};
    String body = jsonEncode(<String, String>{
      'refreshToken': refreshToken,
    });

    final response = await http.post(url, headers: headers, body: body);
    TokenManager token;
    if (response.body != "Unauthorized") {
      token = TokenManager.fromJson(json.decode(response.body));
      token.statusCode = response.statusCode;
    }

    if (response.statusCode == 200) {
      SharedPreferences prefs = await SharedPreferences.getInstance();
      prefs.setString('token', token.jwt);
    }
    return token;
  }

Server config for HTTP and WS : 

const PORT = process.env.PORT || 8080;

const http = require('http');
const WebSocket = require('ws');
const askless = require("askless");

const serverDatabase = http.createServer(app);
const serverWebsocket = new askless.AsklessServer();

serverWebsocket.init({
  projectName: 'XXXX',
  sendInternalErrorsToClient: false,
  logger: {
      useDefaultLogger: true
  },
  wsOptions : {
      port: PORT,
      server: serverDatabase,
  },
  requestTimeoutInSeconds: 15
});

serverWebsocket.start();

serverDatabase.listen(8081);

Do you have an idea of what I do wrong please ?

Thanks

**Comment by RodrigoBertotti** [comment]
Hi! Thanks!
With Askless you can do all your app operations in the Askless framework, you don't need to have a HTTP server, check out the [server documentation](https://github.com/WiseTap/Askless/blob/dev/documentation/english_documentation.md)
The message "upgrade required" appears when you try to access a websocket server using the browser  (The Askless framework uses WebSocket)
If you want to still use a HTTP server, I highly recommend to create a separated project in your Heroku account
